/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIdeasRouteImport } from './routes/_authenticated/ideas'
import { Route as AuthenticatedStreamsIndexRouteImport } from './routes/_authenticated/streams.index'
import { Route as AuthenticatedStreamsStreamIdRouteImport } from './routes/_authenticated/streams.$streamId'
import { Route as AuthenticatedYoutubeIndexRouteImport } from './routes/_authenticated/youtube.index'
import { Route as AuthenticatedYoutubeVideoIdRouteImport } from './routes/_authenticated/youtube.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdeasRoute = AuthenticatedIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStreamsIndexRoute =
  AuthenticatedStreamsIndexRouteImport.update({
    id: '/streams/',
    path: '/streams/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStreamsStreamIdRoute =
  AuthenticatedStreamsStreamIdRouteImport.update({
    id: '/streams/$streamId',
    path: '/streams/$streamId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYoutubeIndexRoute =
  AuthenticatedYoutubeIndexRouteImport.update({
    id: '/youtube/',
    path: '/youtube/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYoutubeVideoIdRoute =
  AuthenticatedYoutubeVideoIdRouteImport.update({
    id: '/youtube/$videoId',
    path: '/youtube/$videoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ideas': typeof AuthenticatedIdeasRoute
  '/streams/$streamId': typeof AuthenticatedStreamsStreamIdRoute
  '/youtube/$videoId': typeof AuthenticatedYoutubeVideoIdRoute
  '/streams/': typeof AuthenticatedStreamsIndexRoute
  '/youtube/': typeof AuthenticatedYoutubeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ideas': typeof AuthenticatedIdeasRoute
  '/streams/$streamId': typeof AuthenticatedStreamsStreamIdRoute
  '/youtube/$videoId': typeof AuthenticatedYoutubeVideoIdRoute
  '/streams': typeof AuthenticatedStreamsIndexRoute
  '/youtube': typeof AuthenticatedYoutubeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ideas': typeof AuthenticatedIdeasRoute
  '/_authenticated/streams/$streamId': typeof AuthenticatedStreamsStreamIdRoute
  '/_authenticated/youtube/$videoId': typeof AuthenticatedYoutubeVideoIdRoute
  '/_authenticated/streams/': typeof AuthenticatedStreamsIndexRoute
  '/_authenticated/youtube/': typeof AuthenticatedYoutubeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/ideas'
    | '/streams/$streamId'
    | '/youtube/$videoId'
    | '/streams/'
    | '/youtube/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/ideas'
    | '/streams/$streamId'
    | '/youtube/$videoId'
    | '/streams'
    | '/youtube'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/ideas'
    | '/_authenticated/streams/$streamId'
    | '/_authenticated/youtube/$videoId'
    | '/_authenticated/streams/'
    | '/_authenticated/youtube/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ideas': {
      id: '/_authenticated/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof AuthenticatedIdeasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/streams/': {
      id: '/_authenticated/streams/'
      path: '/streams'
      fullPath: '/streams/'
      preLoaderRoute: typeof AuthenticatedStreamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/streams/$streamId': {
      id: '/_authenticated/streams/$streamId'
      path: '/streams/$streamId'
      fullPath: '/streams/$streamId'
      preLoaderRoute: typeof AuthenticatedStreamsStreamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/youtube/': {
      id: '/_authenticated/youtube/'
      path: '/youtube'
      fullPath: '/youtube/'
      preLoaderRoute: typeof AuthenticatedYoutubeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/youtube/$videoId': {
      id: '/_authenticated/youtube/$videoId'
      path: '/youtube/$videoId'
      fullPath: '/youtube/$videoId'
      preLoaderRoute: typeof AuthenticatedYoutubeVideoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIdeasRoute: typeof AuthenticatedIdeasRoute
  AuthenticatedStreamsStreamIdRoute: typeof AuthenticatedStreamsStreamIdRoute
  AuthenticatedYoutubeVideoIdRoute: typeof AuthenticatedYoutubeVideoIdRoute
  AuthenticatedStreamsIndexRoute: typeof AuthenticatedStreamsIndexRoute
  AuthenticatedYoutubeIndexRoute: typeof AuthenticatedYoutubeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIdeasRoute: AuthenticatedIdeasRoute,
  AuthenticatedStreamsStreamIdRoute: AuthenticatedStreamsStreamIdRoute,
  AuthenticatedYoutubeVideoIdRoute: AuthenticatedYoutubeVideoIdRoute,
  AuthenticatedStreamsIndexRoute: AuthenticatedStreamsIndexRoute,
  AuthenticatedYoutubeIndexRoute: AuthenticatedYoutubeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
